### ISSUE TITLE
where is NYP lab1?

### ISSUE THREAD

**Issue by ensargx** [mertgulerx/notesCS#1]
also nyp uygulama1

**Comment by mertgulerx** [comment]
you mean the codes?

**Comment by ensargx** [comment]
> you mean the codes?

yep

**Comment by mertgulerx** [comment]
They are all in my oopProjects repo. 

Visa application system is 1-1 of the lab1.

And the Reservation System is a updated version of uygulama1.

**Comment by mertgulerx** [comment]
Keep in mind that in exams they dont want user input. So my reservation system is not valid for exams. Check this code for uygulama1. https://drive.google.com/file/d/1O0tjAEwGkqh28Ir7BMERNML7RmPBJGE_/view

**Comment by ensargx** [comment]
OK. then. I thought this repo was for all CS class notes and stuff.

**Comment by mertgulerx** [comment]
may add more to this repo later
